name: 'Upload to Maven Central'
description: 'Creates bundle from existing artifacts and uploads to Maven Central without rebuilding'

inputs:
  release-version:
    description: 'Release version to upload'
    required: true
  sonatype-username:
    description: 'Sonatype username'
    required: true
  sonatype-password:
    description: 'Sonatype password'
    required: true
  gpg-private-key:
    description: 'GPG private key for signing'
    required: true
  gpg-passphrase:
    description: 'GPG passphrase'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Upload to Maven Central
      shell: bash
      run: |
        cd ${{ github.workspace }}
        ./gradlew :core:uploadToCentralPortal --no-daemon \
          -Pversion="${{ inputs.release-version }}"
      env:
        SONATYPE_USERNAME: ${{ inputs.sonatype-username }}
        SONATYPE_PASSWORD: ${{ inputs.sonatype-password }}
        GPG_PRIVATE_KEY: ${{ inputs.gpg-private-key }}
        GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
